### PR TITLE
Add snyk for testing vulnerabilities

### PR DESCRIPTION
**Pull request by lukasz-kaniowski**
Automatic testing for known vulnerabilities using [snyk.io](https://snyk.io/)
It found 1, details can be found here [Regular Expression Denial of Service](https://snyk.io/test/github/lm-tools/feedback/1cbbade7a36b840a70c282fd5e1469a5e806a21b?fromStatus=true)

### CODE REVIEW

**Comment by lukasz-kaniowski** [comment]
@gjvis is there anything more that we could do to add more superpowers from snyk.io ?

**Comment by nathancashmoredwp** [comment]
👍

**Comment by gjvis** [comment]
@lukasz-kaniowski you should try out the Github integration (its free for public repos) – sign up with your Github account at snyk.io, click on "Test my Github repositories", and then click "Watch" on your NodeJS repos. We'll monitor them, and if they become vulnerable we'll email you, and automatically open a PR to resolve the vulnerabilities (it'll upgrade deps where possible, falling back to applying patches if it can't upgrade).

Also: we should catch up about how everything is going (here and there) over 🍻!

**Comment by lukasz-kaniowski** [comment]
@gjvis I've add integration already. Seems neat. And strong 👍 for a 🍻

**Comment by nathancashmoredwp** [comment]
+ 1

**Pull request merged**
